CREATE TABLE [adw].[AHR_Population_History] (
    [URN]                INT            IDENTITY (1, 1) NOT NULL,
    [CreatedDate]        DATETIME       DEFAULT (getdate()) NULL,
    [CreatedBy]          VARCHAR (20)   DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]    DATETIME       DEFAULT (getdate()) NULL,
    [LastUpdatedBy]      VARCHAR (20)   DEFAULT (suser_sname()) NULL,
    [AdiKey]             INT            NULL,
    [SrcFileName]        VARCHAR (100)  NULL,
    [AdiTableName]       VARCHAR (100)  NULL,
    [LoadDate]           DATE           NULL,
    [DataDate]           DATE           NULL,
    [ClientKey]          INT            NULL,
    [ACE_ID]             NUMERIC (15)   NULL,
    [ClientMemberKey]    VARCHAR (50)   NOT NULL,
    [EffectiveAsOfDate]  DATE           NULL,
    [HICN]               VARCHAR (50)   NULL,
    [MBI]                VARCHAR (50)   NULL,
    [FirstName]          VARCHAR (50)   NULL,
    [LastName]           VARCHAR (50)   NULL,
    [Sex]                VARCHAR (1)    NULL,
    [DOB]                DATE           NULL,
    [CurrentRS]          DECIMAL (5, 4) DEFAULT ((0)) NULL,
    [CurrentDisplayGaps] INT            DEFAULT ((0)) NULL,
    [CurrentGaps]        INT            DEFAULT ((0)) NULL,
    [Age]                INT            NULL,
    [TIN]                VARCHAR (50)   NULL,
    [TIN_NAME]           VARCHAR (100)  NULL,
    [NPI]                VARCHAR (50)   NULL,
    [NPI_NAME]           VARCHAR (100)  NULL,
    [PRIM_SPECIALTY]     VARCHAR (100)  NULL,
    [RUN_DATE]           DATE           NULL,
    [RUN_YEAR]           INT            NULL,
    [RUN_MTH]            INT            NULL,
    [LOAD_DATE]          DATE           DEFAULT (sysdatetime()) NULL,
    [LOAD_USER]          VARCHAR (50)   DEFAULT (suser_sname()) NULL,
    [ToSend]             VARCHAR (1)    DEFAULT ('Y') NULL,
    [SentDate]           DATE           NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

