CREATE TABLE [adw].[FctEDVisits] (
    [FctEDVisitsSkey]       INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]           DATETIME      DEFAULT (getdate()) NULL,
    [CreatedBy]             VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]       DATETIME      DEFAULT (getdate()) NULL,
    [LastUpdatedBy]         VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [AdiKey]                INT           NULL,
    [adiTableName]          VARCHAR (100) NULL,
    [SrcFileName]           VARCHAR (100) NULL,
    [LoadDate]              DATE          NULL,
    [DataDate]              DATE          NULL,
    [ClientKey]             INT           NULL,
    [ClientMemberKey]       VARCHAR (50)  NULL,
    [EffectiveAsOfDate]     DATE          NULL,
    [SEQ_ClaimID]           VARCHAR (50)  NULL,
    [PrimaryServiceDate]    DATE          NULL,
    [PrimaryDiagnosis]      VARCHAR (100) NULL,
    [RevCode]               INT           NULL,
    [VendorID]              VARCHAR (20)  NULL,
    [VendorName]            VARCHAR (100) NULL,
    [SVCProviderID]         VARCHAR (20)  NULL,
    [SVCProviderFullName]   VARCHAR (100) NULL,
    [AttProviderID]         VARCHAR (20)  NULL,
    [AttProviderFullName]   VARCHAR (100) NULL,
    [LOS]                   INT           NULL,
    [ClaimType]             VARCHAR (20)  NULL,
    [BillType]              VARCHAR (5)   NULL,
    [AttribNPI]             VARCHAR (10)  NULL,
    [AttribTIN]             VARCHAR (10)  NULL,
    [FacilityPrefferedFlag] CHAR (1)      NULL,
    [ERToIPFlag]            INT           DEFAULT ((0)) NULL,
    [ObvFlag]               INT           DEFAULT ((0)) NULL,
    [SvcNPISpecialty]       VARCHAR (30)  NULL,
    [AttNPISpecialty]       VARCHAR (30)  NULL,
    [DischDispo]            VARCHAR (2)   NULL,
    [SurFlag]               INT           DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([FctEDVisitsSkey] ASC)
);

