CREATE TABLE [adw].[FctMembership_Dev] (
    [FctMembershipSkey]           INT             IDENTITY (1, 1) NOT NULL,
    [CreatedDate]                 DATETIME        DEFAULT (getdate()) NULL,
    [CreatedBy]                   VARCHAR (20)    DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]             DATETIME        DEFAULT (getdate()) NULL,
    [LastUpdatedBy]               VARCHAR (20)    DEFAULT (suser_sname()) NULL,
    [LoadDate]                    DATE            NULL,
    [DataDate]                    DATE            NULL,
    [MbrMemberKey]                INT             DEFAULT ((0)) NOT NULL,
    [MbrDemographicKey]           INT             DEFAULT ((0)) NOT NULL,
    [MbrPlanKey]                  INT             DEFAULT ((0)) NOT NULL,
    [MbrCsPlanKey]                INT             DEFAULT ((0)) NOT NULL,
    [MbrPCPKey]                   INT             DEFAULT ((0)) NOT NULL,
    [MbrPhoneKey_Home]            INT             DEFAULT ((0)) NOT NULL,
    [MbrPhoneKey_Mobile]          INT             DEFAULT ((0)) NOT NULL,
    [MbrPhoneKey_Work]            INT             DEFAULT ((0)) NOT NULL,
    [MbrAddressKey_Home]          INT             DEFAULT ((0)) NOT NULL,
    [MbrAddressKey_Work]          INT             DEFAULT ((0)) NOT NULL,
    [MbrEmailKey]                 INT             DEFAULT ((0)) NOT NULL,
    [MbrRespPartyKey]             INT             DEFAULT ((0)) NOT NULL,
    [RowEffectiveDate]            DATE            DEFAULT ('01/01/1900') NOT NULL,
    [RowExpirationDate]           DATE            DEFAULT ('12/31/2099') NOT NULL,
    [Ace_ID]                      NUMERIC (15)    NULL,
    [ClientMemberKey]             VARCHAR (50)    NULL,
    [ClientKey]                   INT             NULL,
    [SubscriberIndicator]         CHAR (1)        DEFAULT ('') NULL,
    [MemberIndicator]             CHAR (1)        DEFAULT ('') NULL,
    [CurrentAge]                  INT             NULL,
    [AgeGroup20Years]             INT             DEFAULT ((0)) NULL,
    [AgeGroup10Years]             INT             DEFAULT ((0)) NULL,
    [AgeGroup5Years]              INT             DEFAULT ((0)) NULL,
    [MbrMonth]                    TINYINT         NULL,
    [MbrYear]                     SMALLINT        NULL,
    [MemberStatus]                VARCHAR (20)    DEFAULT ('') NULL,
    [EnrollementStatus]           VARCHAR (10)    DEFAULT ('') NULL,
    [AceRiskScore]                DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [AceRiskScoreLevel]           DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [ClientRiskScore]             DECIMAL (10, 2) DEFAULT ((0)) NULL,
    [ClientRiskScoreLevel]        DECIMAL (25, 2) DEFAULT ((0)) NULL,
    [RiskScoreUtilization]        DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [RiskScoreClinical]           DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [RiskScoreHRA]                DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [RiskScorePlaceHolder]        DECIMAL (5, 2)  DEFAULT ((0)) NULL,
    [EnrollmentYear]              SMALLINT        DEFAULT ((0)) NULL,
    [EnrollmentQuarter]           TINYINT         DEFAULT ((0)) NULL,
    [EnrollmentYearQuarter]       TINYINT         DEFAULT ((0)) NULL,
    [EnrollmentYearMonth]         TINYINT         DEFAULT ((0)) NULL,
    [EligibleYear]                SMALLINT        DEFAULT ((0)) NULL,
    [EligibilityQuarter]          TINYINT         DEFAULT ((0)) NULL,
    [EligibilityYearQuarter]      TINYINT         DEFAULT ((0)) NULL,
    [EligibilityYearMonth]        TINYINT         DEFAULT ((0)) NULL,
    [MemberCount]                 TINYINT         DEFAULT ((0)) NULL,
    [AvgMemberCount]              TINYINT         DEFAULT ((0)) NULL,
    [SubscriberCount]             TINYINT         DEFAULT ((0)) NULL,
    [AvgSubscriberCount]          TINYINT         DEFAULT ((0)) NULL,
    [PersonCreatedCount]          TINYINT         DEFAULT ((0)) NULL,
    [MemberMonths]                TINYINT         DEFAULT ((0)) NULL,
    [SubscriberMonths]            TINYINT         DEFAULT ((0)) NULL,
    [FamilyRatio]                 TINYINT         DEFAULT ((0)) NULL,
    [AvgAge]                      TINYINT         DEFAULT ((0)) NULL,
    [NoOfMonths]                  TINYINT         DEFAULT ((0)) NULL,
    [MemberCurrentEffectiveDate]  DATE            NULL,
    [MemberCurrentExpirationDate] DATE            NULL,
    [Active]                      BIT             NULL,
    [Excluded]                    BIT             DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([FctMembershipSkey] ASC)
);

