CREATE TABLE [adw].[FctQMCalc] (
    [FctQMCalcKey]       INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]        DATETIME      DEFAULT (getdate()) NULL,
    [CreatedBy]          VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]    DATETIME      DEFAULT (getdate()) NULL,
    [LastUpdatedBy]      VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [AdiKey]             INT           NULL,
    [adiTableName]       VARCHAR (100) NULL,
    [SrcFileName]        VARCHAR (100) NULL,
    [LoadDate]           DATE          NULL,
    [DataDate]           DATE          NULL,
    [ClientKey]          INT           NULL,
    [ClientMemberKey]    VARCHAR (50)  NULL,
    [EffectiveAsOfDate]  DATE          NULL,
    [PrimSvcYr]          INT           NULL,
    [PrimSvcMth]         INT           NULL,
    [Seq_ClaimID]        VARCHAR (50)  NULL,
    [PrimaryServiceDate] DATE          NULL,
    [ValueCodeSystem]    VARCHAR (25)  NULL,
    [ValueCode]          VARCHAR (25)  NULL,
    [QmMsrID]            VARCHAR (50)  NULL,
    [QmDate]             DATE          NULL,
    [AttribNPI]          VARCHAR (10)  NULL,
    [AttribTIN]          VARCHAR (10)  NULL,
    [AddressedFlg]       INT           DEFAULT ((0)) NULL,
    [AddressedSrc]       VARCHAR (30)  NULL,
    [AddressedDate]      DATE          NULL,
    PRIMARY KEY CLUSTERED ([FctQMCalcKey] ASC)
);

