CREATE TABLE [adw].[FctReadmissionVisits] (
    [FctReadmissionVisitsKey] INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]             DATETIME      DEFAULT (getdate()) NULL,
    [CreatedBy]               VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]         DATETIME      DEFAULT (getdate()) NULL,
    [LastUpdatedBy]           VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [AdiKey]                  INT           NULL,
    [adiTableName]            VARCHAR (100) NULL,
    [SrcFileName]             VARCHAR (100) NULL,
    [LoadDate]                DATE          NULL,
    [DataDate]                DATE          NULL,
    [ClientKey]               INT           NULL,
    [ClientMemberKey]         VARCHAR (50)  NULL,
    [EffectiveAsOfDate]       DATE          NULL,
    [SEQ_ClaimID]             VARCHAR (50)  NULL,
    [PrimaryServiceDate]      DATE          NULL,
    [AdmissionDate]           DATE          NULL,
    [DischargeDate]           DATE          NULL,
    [DischargeDisposition]    INT           NULL,
    [DrgCode]                 VARCHAR (20)  NULL,
    [PrimaryDiagnosis]        VARCHAR (100) NULL,
    [VendorID]                VARCHAR (20)  NULL,
    [VendorName]              VARCHAR (100) NULL,
    [SVCProviderID]           VARCHAR (20)  NULL,
    [SVCProviderFullName]     VARCHAR (150) NULL,
    [SNFPreferredFlag]        CHAR (1)      NULL,
    [FacilityPrefferedFlag]   CHAR (1)      NULL,
    [LOS]                     INT           NULL,
    [ClaimType]               VARCHAR (20)  NULL,
    [BillType]                VARCHAR (5)   NULL,
    [AttribNPI]               VARCHAR (10)  NULL,
    [AttribTIN]               VARCHAR (10)  NULL,
    [InstType]                VARCHAR (10)  NULL,
    [AssocSEQ_ClaimID]        VARCHAR (50)  NULL,
    [AssocDischargeDate]      DATE          NULL,
    PRIMARY KEY CLUSTERED ([FctReadmissionVisitsKey] ASC)
);

