CREATE TABLE [adw].[FctVisitCodes] (
    [FctVisitCodesKey]   INT           IDENTITY (1, 1) NOT NULL,
    [CreatedDate]        DATETIME      DEFAULT (getdate()) NULL,
    [CreatedBy]          VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]    DATETIME      DEFAULT (getdate()) NULL,
    [LastUpdatedBy]      VARCHAR (20)  DEFAULT (suser_sname()) NULL,
    [AdiKey]             INT           NULL,
    [adiTableName]       VARCHAR (100) NULL,
    [SrcFileName]        VARCHAR (100) NULL,
    [LoadDate]           DATE          NULL,
    [DataDate]           DATE          NULL,
    [ClientKey]          INT           NULL,
    [ClientMemberKey]    VARCHAR (50)  NULL,
    [EffectiveAsOfDate]  DATE          NULL,
    [SEQ_ClaimID]        VARCHAR (50)  NULL,
    [ClaimType]          VARCHAR (20)  NULL,
    [PrimaryServiceDate] DATE          NULL,
    [DRGCode]            VARCHAR (10)  NULL,
    [MDCCode]            VARCHAR (10)  NULL,
    [PrimDx]             VARCHAR (15)  NULL,
    [PrimPC]             VARCHAR (15)  NULL,
    [PrimCPT]            VARCHAR (15)  NULL,
    [ERFlg]              INT           DEFAULT ((0)) NULL,
    [ObvFlg]             INT           DEFAULT ((0)) NULL,
    [SurFlg]             INT           DEFAULT ((0)) NULL,
    [SvcNPISpecialty]    VARCHAR (30)  NULL,
    [AttNPISpecialty]    VARCHAR (30)  NULL,
    [DrgType]            VARCHAR (2)   NULL,
    PRIMARY KEY CLUSTERED ([FctVisitCodesKey] ASC)
);

