CREATE TABLE [adw].[MbrPlan] (
    [mbrPlanKey]           INT           IDENTITY (1, 1) NOT NULL,
    [ClientMemberKey]      VARCHAR (50)  NOT NULL,
    [ClientKey]            INT           NULL,
    [adiKey]               INT           NOT NULL,
    [adiTableName]         VARCHAR (100) NOT NULL,
    [IsCurrent]            CHAR (1)      CONSTRAINT [DF_mbrPlan_recordFlag] DEFAULT ('Y') NOT NULL,
    [EffectiveDate]        DATE          NOT NULL,
    [ExpirationDate]       DATE          CONSTRAINT [DF_MbrPlanExpirationDate] DEFAULT ('12/31/9999') NOT NULL,
    [ProductPlan]          VARCHAR (20)  NOT NULL,
    [ProductSubPlan]       VARCHAR (20)  NOT NULL,
    [ProductSubPlanName]   VARCHAR (50)  NOT NULL,
    [MbrIsDualCoverage]    TINYINT       CONSTRAINT [DF_MbrPlanMbrIsDualCoverage] DEFAULT ((-1)) NOT NULL,
    [DualEligiblityStatus] CHAR (2)      DEFAULT ((99)) NOT NULL,
    [ClientPlanEffective]  DATE          NULL,
    [LoadDate]             DATE          NOT NULL,
    [DataDate]             DATE          NOT NULL,
    [CreatedDate]          DATETIME2 (7) CONSTRAINT [DF_MbrPlan_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            VARCHAR (50)  CONSTRAINT [DF_MbrPlan_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]      DATETIME2 (7) CONSTRAINT [DF_MbrPlan_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]        VARCHAR (50)  CONSTRAINT [DF_MbrPlan_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    PRIMARY KEY CLUSTERED ([mbrPlanKey] ASC),
    CONSTRAINT [CK_MbrPlanMbrIsDualCoverage] CHECK ([MbrIsDualCoverage]=(0) OR [MbrIsDualCoverage]=(1) OR [MbrIsDualCoverage]=(-1))
);

