CREATE TABLE [adw].[z_tmp_RSCalc] (
    [EffectiveAsOfDate]       DATE         NULL,
    [ClientKey]               INT          NULL,
    [ClientMemberKey]         VARCHAR (75) NULL,
    [Wt_A]                    FLOAT (53)   NULL,
    [Wt_B]                    FLOAT (53)   NULL,
    [Wt_C]                    FLOAT (53)   NULL,
    [Wt_D]                    FLOAT (53)   NULL,
    [Wt_E]                    FLOAT (53)   NULL,
    [Wt_F]                    FLOAT (53)   NULL,
    [Wt_G]                    FLOAT (53)   NULL,
    [Wt_TotalHCC]             FLOAT (53)   NULL,
    [Wt_TotalRSDisease]       FLOAT (53)   NULL,
    [ClientRiskScore]         FLOAT (53)   NULL,
    [TSPct_Rank]              FLOAT (53)   NULL,
    [ClientRiskScorePct_Rank] FLOAT (53)   NULL,
    [PrimSvcDate_Start]       DATE         NULL,
    [PrimSvcDate_End]         DATE         NULL,
    [CY]                      INT          NULL,
    [PY]                      INT          NULL,
    [SUBSCRIBER_ID]           VARCHAR (50) NULL,
    [CY_TotalPaid]            MONEY        NULL,
    [PY_TotalPaid]            MONEY        NULL,
    [CRY_TotalPaid]           MONEY        NULL,
    [PRY_TotalPaid]           MONEY        NULL,
    [CRY_PhyPaid]             MONEY        NULL,
    [CRY_IPPaid]              MONEY        NULL,
    [CRY_OPPaid]              MONEY        NULL
);

