CREATE TABLE [ast].[MbrInfoStg2_MbrDataUpdate] (
    [mbrInfoStg2_MbrDataKey]     INT           IDENTITY (1, 1) NOT NULL,
    [ClientMemberKey]            VARCHAR (50)  NULL,
    [ClientKey]                  VARCHAR (50)  NULL,
    [MstrMrnKey]                 NUMERIC (15)  CONSTRAINT [DF_astMbrInfoStg2_MbrDataUpdateMstrMrnKey] DEFAULT ((0)) NOT NULL,
    [LoadType]                   VARCHAR (5)   CONSTRAINT [DF_astMbrInfoStg2_MbrDataUpdate_LoadType] DEFAULT ('P') NULL,
    [mbrLastName]                VARCHAR (100) NULL,
    [mbrFirstName]               VARCHAR (100) NULL,
    [mbrMiddleName]              VARCHAR (100) NULL,
    [prvNPI]                     VARCHAR (10)  NULL,
    [prvTIN]                     VARCHAR (10)  NULL,
    [prvAutoAssign]              VARCHAR (10)  NULL,
    [prvClientEffective]         DATE          NULL,
    [prvClientExpiration]        DATE          NULL,
    [SrcFileName]                VARCHAR (100) NULL,
    [AdiTableName]               VARCHAR (100) NULL,
    [AdiKey]                     INT           NULL,
    [stgRowAction]               VARCHAR (20)  DEFAULT ('Upsert') NOT NULL,
    [stgRowStatus]               VARCHAR (20)  CONSTRAINT [DF_astMbrInfoStg2_MbrDataUpdate_StgRowStatus] DEFAULT ('Valid') NOT NULL,
    [LoadDate]                   DATE          NULL,
    [DataDate]                   DATE          NULL,
    [CreateDate]                 DATETIME      CONSTRAINT [DF_astMbrInfoStg2_MbrDataUpdate_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]                   VARCHAR (50)  CONSTRAINT [DF_astMbrInfoStg2_MbrDataUpdate_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [TransformPcpEffectiveDate]  DATE          CONSTRAINT [DF_TransfromPcpEffectiveDate] DEFAULT ('1900/01/01') NULL,
    [TransfromPcpExpirationDate] DATE          CONSTRAINT [DF_TransfromPcpExpirationDate] DEFAULT ('1900/01/01') NULL,
    PRIMARY KEY CLUSTERED ([mbrInfoStg2_MbrDataKey] ASC),
    CONSTRAINT [CK_astMbrInfoStg2_MbrDataUpdate_stgRowStatus] CHECK ([stgRowStatus]='Exported' OR [stgRowStatus]='Valid' OR [stgRowStatus]='Loaded' OR [stgRowStatus]='Not Valid')
);

