CREATE TABLE [ast].[MbrModelMbrData] (
    [MbrModelMbrDataKey]            INT           IDENTITY (1, 1) NOT NULL,
    [ClientSubscriberId]            VARCHAR (50)  NULL,
    [ClientKey]                     VARCHAR (50)  NULL,
    [MstrMrnKey]                    NUMERIC (15)  CONSTRAINT [DF_astMbrStg2_MbrData_MstrMrnKey] DEFAULT ((-1)) NOT NULL,
    [LoadType]                      VARCHAR (5)   CONSTRAINT [DF_astMbrStg2_MbrData_LoadType] DEFAULT ('P') NULL,
    [mbrLastName]                   VARCHAR (100) NULL,
    [mbrFirstName]                  VARCHAR (100) NULL,
    [mbrMiddleName]                 VARCHAR (100) NULL,
    [mbrSSN]                        VARCHAR (15)  NULL,
    [mbrGENDER]                     VARCHAR (5)   NULL,
    [mbrDob]                        DATE          NULL,
    [mbrInsuranceCardIdNum]         VARCHAR (20)  NULL,
    [mbrMEDICAID_NO]                VARCHAR (15)  NULL,
    [mbrMEDICARE_ID]                VARCHAR (15)  NULL,
    [HICN]                          VARCHAR (11)  NULL,
    [MBI]                           VARCHAR (11)  NULL,
    [mbrEthnicity]                  VARCHAR (20)  NULL,
    [mbrRace]                       VARCHAR (20)  NULL,
    [mbrPrimaryLanguage]            VARCHAR (20)  NULL,
    [prvNPI]                        VARCHAR (10)  NULL,
    [prvTIN]                        VARCHAR (10)  NULL,
    [prvAutoAssign]                 VARCHAR (10)  NULL,
    [prvClientEffective]            DATE          NULL,
    [prvClientExpiration]           DATE          NULL,
    [plnProductPlan]                VARCHAR (20)  NULL,
    [plnProductSubPlan]             VARCHAR (20)  NULL,
    [plnProductSubPlanName]         VARCHAR (50)  NULL,
    [plnMbrIsDualCoverage]          VARCHAR (20)  NULL,
    [plnClientPlanEffective]        DATE          NULL,
    [rspLastName]                   VARCHAR (100) NULL,
    [rspFirstName]                  VARCHAR (100) NULL,
    [rspAddress1]                   VARCHAR (100) NULL,
    [rspAddress2]                   VARCHAR (100) NULL,
    [rspCITY]                       VARCHAR (65)  NULL,
    [rspSTATE]                      CHAR (25)     NULL,
    [rspZIP]                        VARCHAR (20)  NULL,
    [rspPhone]                      VARCHAR (30)  NULL,
    [SrcFileName]                   VARCHAR (100) NULL,
    [AdiTableName]                  VARCHAR (100) NULL,
    [AdiKey]                        INT           NULL,
    [stgRowStatus]                  VARCHAR (20)  CONSTRAINT [DF_astMbrStg2_MbrData_StgRowStatus] DEFAULT ('Not Valid') NOT NULL,
    [LoadDate]                      DATE          NULL,
    [DataDate]                      DATE          NULL,
    [CreateDate]                    DATETIME      CONSTRAINT [DF_astMbrStg2_MbrData_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]                      VARCHAR (50)  CONSTRAINT [DF_astMbrStg2_MbrData_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [MbrMemberKey]                  INT           NULL,
    [MbrPlanKey]                    INT           NULL,
    [MbrPcpKey]                     INT           NULL,
    [MbrCsPlanKey]                  INT           NULL,
    [TransformPcpEffectiveDate]     DATE          DEFAULT ('1/1/1900') NULL,
    [TransfromPcpExpirationDate]    DATE          DEFAULT ('1/1/1900') NULL,
    [TransformPlanEffectiveDate]    DATE          DEFAULT ('1/1/1900') NULL,
    [TransfromPlanExpirationDate]   DATE          DEFAULT ('1/1/1900') NULL,
    [TransformCsPlanEffectiveDate]  DATE          DEFAULT ('1/1/1900') NULL,
    [TransfromCsPlanExpirationDate] DATE          DEFAULT ('1/1/1900') NULL,
    [MbrLoadHistoryKey]             INT           NULL,
    [TransformDemoEffectiveDate]    DATE          NULL,
    [TransformDemoExpirationDate]   DATE          NULL,
    [TransformCsPlanNameDate]       VARCHAR (50)  NULL,
    [plnClientPlanEndDate]          DATE          NULL,
    [stgRowAction]                  VARCHAR (10)  DEFAULT ('Upsert') NOT NULL,
    [Member_Dual_Eligible_Flag]     VARCHAR (20)  NULL,
    [mbrDOD]                        DATE          DEFAULT ('1900-01-01') NULL,
    [ProviderPOD]                   VARCHAR (50)  NULL,
    [ProviderChapter]               VARCHAR (50)  NULL,
    [ProviderPracticeName]          VARCHAR (100) NULL,
    [ProviderFirstName]             VARCHAR (100) NULL,
    [ProviderLastName]              VARCHAR (50)  NULL,
    [ProviderMI]                    VARCHAR (50)  NULL,
    [ProviderSpecialty]             VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MbrModelMbrDataKey] ASC),
    CONSTRAINT [CK_MbrStg2_MbrData_stgRowStatus] CHECK ([stgRowStatus]='Exported' OR [stgRowStatus]='Valid' OR [stgRowStatus]='Loaded' OR [stgRowStatus]='Not Valid')
);


GO
CREATE NONCLUSTERED INDEX [astMbrModelMbrData_StgRowStatusLoadDate]
    ON [ast].[MbrModelMbrData]([stgRowStatus] ASC, [LoadDate] ASC)
    INCLUDE([ClientSubscriberId], [ClientKey], [mbrLastName], [mbrFirstName], [mbrMiddleName], [mbrSSN], [mbrGENDER], [mbrDob], [mbrMEDICAID_NO], [mbrMEDICARE_ID], [HICN], [MBI], [mbrEthnicity], [mbrRace], [mbrPrimaryLanguage], [AdiTableName], [AdiKey], [DataDate]);

