CREATE TABLE [lst].[lstNdcDrugProduct] (
    [CreatedDate]                   DATETIME       DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                     VARCHAR (50)   DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]                 VARCHAR (50)   DEFAULT (suser_sname()) NOT NULL,
    [SrcFileName]                   VARCHAR (100)  NULL,
    [lstNdcDrugProductKey]          INT            IDENTITY (1, 1) NOT NULL,
    [PRODUCTID]                     VARCHAR (60)   NULL,
    [PRODUCTNDC]                    VARCHAR (20)   NULL,
    [PRODUCTTYPENAME]               VARCHAR (50)   NULL,
    [PROPRIETARYNAME]               VARCHAR (2500) NULL,
    [PROPRIETARYNAMESUFFIX]         VARCHAR (250)  NULL,
    [NONPROPRIETARYNAME]            VARCHAR (1000) NULL,
    [DOSAGEFORMNAME]                VARCHAR (50)   NULL,
    [ROUTENAME]                     VARCHAR (500)  NULL,
    [STARTMARKETINGDATE]            VARCHAR (10)   NULL,
    [ENDMARKETINGDATE]              VARCHAR (10)   NULL,
    [MARKETINGCATEGORYNAME]         VARCHAR (50)   NULL,
    [APPLICATIONNUMBER]             VARCHAR (20)   NULL,
    [LABELERNAME]                   VARCHAR (400)  NULL,
    [SUBSTANCENAME]                 VARCHAR (5000) NULL,
    [ActiveNumeratorStrength]       VARCHAR (5000) NULL,
    [ActiveIngredUnit]              VARCHAR (5000) NULL,
    [PharmClasses]                  VARCHAR (5000) NULL,
    [DEASCHEDULE]                   VARCHAR (10)   NULL,
    [NdcExcludeFlag]                CHAR (1)       NULL,
    [ListingRecordCertifiedThrough] DATE           NULL,
    [ACTIVE]                        CHAR (1)       DEFAULT ('Y') NULL,
    [EffectiveDate]                 DATE           DEFAULT (getdate()) NULL,
    [ExpirationDate]                DATE           DEFAULT ('2099-12-31') NULL,
    [Status]                        CHAR (1)       NULL,
    PRIMARY KEY CLUSTERED ([lstNdcDrugProductKey] ASC)
);

