


CREATE FUNCTION [adw].[2020_tvf_Get_ActiveMembersFull]
(@EffDate		DATE
)
RETURNS TABLE
AS
RETURN

( 
SELECT [ClientKey]
      ,[Ace_ID]
      ,[ClientMemberKey]
      ,[MBI]
      ,[HICN]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Gender]
      ,[DOB]
      ,[DOD]
      ,[CurrentAge]
      ,[MbrMonth]
      ,[MbrYear]
      ,[LanguageCode]
      ,[Ethnicity]
      ,[Race]
      ,[MemberHomeAddress]
      ,[MemberHomeAddress1]
      ,[MemberHomeCity]
      ,[MemberHomeState]
	  ,[MemberPhone]
	  ,[MemberCellPhone]
	  ,[MemberHomePhone]
      ,[CountyName]
      ,[CountyNumber]
      ,[Region]
      ,[POD]
      ,[MemberHomeZip]
      ,[MemberMailingAddress]
      ,[MemberMailingAddress1]
      ,[MemberMailingCity]
      ,[MemberMailingState]
      ,[MedicaidMedicareDualEligibleIndicator]
      ,[PersonMonthCreatedfromClaimIndicator]
      ,[MemberStatus]
      ,[EnrollementStatus]
      ,[MemberID]
      ,[MedicaidID]
      ,[CardID]
      ,[FamilyID]
      ,[BenefitType]
      ,[LOB]
      ,[PlanID]
      ,[ProductCode]
      ,[SubgrpID]
      ,[SubgrpName]
      ,[PlanName]
      ,[PlanType]
      ,[PlanTier]
      ,[Contract]
      ,[NPI]
      ,[PcpPracticeTIN]
      ,[ProviderFirstName]
	  ,[ProviderMI]
      ,[ProviderLastName]
      ,[ProviderPracticeName]
      ,[ProviderAddressLine1]
      ,[ProviderAddressLine2]
      ,[ProviderCity]
      ,[ProviderCounty]
      ,[ProviderZip]
      ,[ProviderPhone]
      ,[ProviderSpecialty]
      ,[ProviderNetwork]
      ,[SpecialistStatus]
      ,[GroupOrPrivatePractice]
      ,[ProviderPOD]
      ,[ProviderChapter]
      ,[AceRiskScore]
      ,[AceRiskScoreLevel]
      ,[ClientRiskScore]
      ,[ClientRiskScoreLevel]
      ,[RiskScoreUtilization]
      ,[RiskScoreClinical]
      ,[RiskScoreHRA]
      ,[RiskScorePlaceHolder]
      ,[EnrollmentYear]
      ,[EnrollmentQuarter]
      ,[EnrollmentYearQuarter]
      ,[EnrollmentYearMonth]
      ,[EligibleYear]
      ,[EligibilityQuarter]
      ,[EligibilityYearQuarter]
      ,[EligibilityYearMonth]
      ,[MemberCount]
      ,[AvgMemberCount]
      ,[SubscriberCount]
      ,[AvgSubscriberCount]
      ,[PersonCreatedCount]
      ,[MemberMonths]
      ,[SubscriberMonths]
      ,[FamilyRatio]
      ,[AvgAge]
      ,[NoOfMonths]
      ,[MemberCurrentEffectiveDate]
      ,[MemberCurrentExpirationDate]
      ,[Active]
	  ,[RwEffectiveDate] 
	  ,[RwExpirationDate]
FROM [ACDW_CLMS_SHCN_MSSP].[adw].[vw_Dashboard_Membership]
WHERE @EffDate BETWEEN [RwEffectiveDate] AND [RwExpirationDate]
AND Active = 1

)
/***
Usage: 
SELECT a.ClientMemberKey
FROM [adw].[2020_tvf_Get_ActiveMembersFull] ('10/15/2020') a
***/


