
--- last modify 02/12/2021 - new code from Si

CREATE  VIEW [adw].[vw_Exp_TexasADAllTMsg_Dev] 
AS 

SELECT  [NtfGhhNotificationKey]
      ,[Facility Name]
      ,[Facility NPI]
      ,[Facility City]
      ,[Facility State]
      ,[Facility Type]
      ,[Visit ID]
      ,[Status]
      ,[AdmitDate]
      ,[DischargeDate]
      ,[Setting]
      ,[Patient ID]
      ,[Last Name]
      ,[First Name]
      ,[Middle Name]
      ,[Suffix]
      ,[DOB]
      ,[Gender]
      ,[Address1]
      ,[Address2]
      ,[Address3]
      ,[City]
      ,[State]
      ,[Zip]
      ,[Mobile Phone]
      ,[Home Phone]
      ,[Patient Phone Number (Unknown source)]
      ,[Primary Insurance Number]
      ,[Primary Insurer]
      ,[Primary Insurance Plan]
      ,[Insurance Billed]
      ,[Other Practices]
      ,[Other Providers]
      ,[Other Programs]
      ,[Facility Visit Id]
      ,[Account Number]
      ,[Admitted From]
      ,[Discharged Disposition]
      ,[Discharge Location]
      ,[MLOA Disposition]
      ,[MLOA Location]
      ,[Admit Care Coordinator]
      ,[Discharge Care Coordinator]
      ,[Entry Delay]
      ,[Visit Duration - (days)]
      ,[LOS]
      ,[CCD]
      ,[Attending Provider NPI]
      ,[Attending Provider Las tName]
      ,[Attending Provider First Name]
      ,[Active Roster Patient]
      ,[Primary Diagnosis Description]
      ,[Primary Diagnosis Code]
      ,[Diagnosis Category]
      ,[Subsequent Diagnosis Codes]
      ,[High Utilizer Flag]
      ,[Readmission Risk Flag]
      ,[Recent SNF Stay Flag]
      ,[Recent Inpatient Stay Flag]
      ,[COVID_19 Flags]
  FROM [ACDW_CLMS_SHCN_MSSP].[adw].[vw_Exp_TexasADTA01Msg_Dev]
  UNION ALL
  SELECT  [NtfGhhNotificationKey]
      ,[Facility Name]
      ,[Facility NPI]
      ,[Facility City]
      ,[Facility State]
      ,[Facility Type]
      ,[Visit ID]
      ,[Status]
      ,[AdmitDate]
      ,[DischargeDate]
      ,[Setting]
      ,[Patient ID]
      ,[Last Name]
      ,[First Name]
      ,[Middle Name]
      ,[Suffix]
      ,[DOB]
      ,[Gender]
      ,[Address1]
      ,[Address2]
      ,[Address3]
      ,[City]
      ,[State]
      ,[Zip]
      ,[Mobile Phone]
      ,[Home Phone]
      ,[Patient Phone Number (Unknown source)]
      ,[Primary Insurance Number]
      ,[Primary Insurer]
      ,[Primary Insurance Plan]
      ,[Insurance Billed]
      ,[Other Practices]
      ,[Other Providers]
      ,[Other Programs]
      ,[Facility Visit Id]
      ,[Account Number]
      ,[Admitted From]
      ,[Discharged Disposition]
      ,[Discharge Location]
      ,[MLOA Disposition]
      ,[MLOA Location]
      ,[Admit Care Coordinator]
      ,[Discharge Care Coordinator]
      ,[Entry Delay]
      ,[Visit Duration - (days)]
      ,[LOS]
      ,[CCD]
      ,[Attending Provider NPI]
      ,[Attending Provider Las tName]
      ,[Attending Provider First Name]
      ,[Active Roster Patient]
      ,[Primary Diagnosis Description]
      ,[Primary Diagnosis Code]
      ,[Diagnosis Category]
      ,[Subsequent Diagnosis Codes]
      ,[High Utilizer Flag]
      ,[Readmission Risk Flag]
      ,[Recent SNF Stay Flag]
      ,[Recent Inpatient Stay Flag]
      ,[COVID_19 Flags]
  FROM [ACDW_CLMS_SHCN_MSSP].[adw].[vw_Exp_TexasADTA03Msg_Dev]



 -- SELECT v1
---  FROM t1
--UNION ALL
--SELECT v2
 -- FROM t2;