CREATE TABLE [adi].[Athena_AWV] (
    [MSSPAWVadiKey]                  INT             IDENTITY (1, 1) NOT NULL,
    [ProgramName]                    VARCHAR (50)    NOT NULL,
    [MeasureName]                    VARCHAR (50)    NOT NULL,
    [ProviderName]                   VARCHAR (50)    NULL,
    [ProviderUsername]               VARCHAR (50)    NULL,
    [NPI]                            VARCHAR (11)    NULL,
    [PatientID]                      VARCHAR (50)    NULL,
    [LastName]                       VARCHAR (50)    NULL,
    [FirstName]                      VARCHAR (50)    NULL,
    [DOBDATE]                        DATE            NULL,
    [Age]                            VARCHAR (10)    NULL,
    [Sex]                            CHAR (1)        NULL,
    [Phone]                          VARCHAR (20)    NULL,
    [RAFScore]                       DECIMAL (10, 3) NULL,
    [GAPScore]                       DECIMAL (10, 3) NULL,
    [Race]                           VARCHAR (50)    NULL,
    [Ethnicity]                      VARCHAR (50)    NULL,
    [Language]                       VARCHAR (50)    NULL,
    [Department_Last_Encounter]      VARCHAR (100)   NULL,
    [LastEncounter]                  VARCHAR (100)   NULL,
    [NextAppointment]                DATE            NULL,
    [ResultStatus]                   VARCHAR (50)    NULL,
    [Result]                         VARCHAR (50)    NULL,
    [SatisfiedDate]                  DATE            NULL,
    [SupportingDocumentation]        VARCHAR (100)   NULL,
    [PrimaryInsurance]               VARCHAR (50)    NULL,
    [PrimaryInsurancePackageType]    VARCHAR (50)    NULL,
    [PrimaryInsurancePolicyNumber]   VARCHAR (50)    NULL,
    [SecondaryInsurance]             VARCHAR (100)   NULL,
    [SecondaryInsurancePackageType]  VARCHAR (50)    NULL,
    [SecondaryInsurancePolicyNumber] VARCHAR (50)    NULL,
    [DateRun]                        DATE            NULL,
    [LoadDate]                       DATE            NOT NULL,
    [DataDate]                       DATE            NOT NULL,
    [srcFileName]                    VARCHAR (100)   NOT NULL,
    [CreatedDate]                    DATETIME        CONSTRAINT [DF_adiMSSP_AWV_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                      VARCHAR (50)    CONSTRAINT [DF_adiMSSP_AWV_CreatedBy] DEFAULT (suser_sname()) NULL,
    [LastUpdatedBy]                  VARCHAR (100)   CONSTRAINT [DF_adiMSSP_AWV_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                DATETIME        CONSTRAINT [DF_adiMSSP_AWV_LastUpdatedDate] DEFAULT (getdate()) NULL,
    [RowStatus]                      TINYINT         DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([MSSPAWVadiKey] ASC)
);

