CREATE TABLE [adi].[Steward_MSSPPartAClaimDiagnosisCode] (
    [MSSPPartAClaimDiagnosisCodeKey]  INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                     VARCHAR (100) NULL,
    [CreateDate]                      DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                        VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                VARCHAR (100) NULL,
    [LastUpdatedBy]                   VARCHAR (100) NULL,
    [LastUpdatedDate]                 DATETIME      NULL,
    [DataDate]                        DATE          NULL,
    [ClaimID]                         VARCHAR (50)  NULL,
    [ICDDiagnosisSEQ]                 VARCHAR (10)  NULL,
    [ICDDiagnosisCategoryCD]          VARCHAR (10)  NULL,
    [ICDDiagnosisCategoryDSC]         VARCHAR (500) NULL,
    [MedicareBeneficiaryID]           VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]         VARCHAR (50)  NULL,
    [ClaimTypeCD]                     VARCHAR (10)  NULL,
    [ClaimTypeDSC]                    VARCHAR (500) NULL,
    [ICDDiagnosisCD]                  VARCHAR (10)  NULL,
    [UmbrellaHealthInsuranceClaimNBR] VARCHAR (50)  NULL,
    [CMSCertificationNBR]             VARCHAR (50)  NULL,
    [ClaimStartDTS]                   DATE          NULL,
    [ClaimEndDTS]                     DATE          NULL,
    [PresentOnAdmitCD]                VARCHAR (10)  NULL,
    [PresentOnAdmitDSC]               VARCHAR (500) NULL,
    [ICDRevisionCD]                   VARCHAR (10)  NULL,
    [FileNM]                          VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartAClaimDiagnosisCodeKey] ASC)
);

