CREATE TABLE [adi].[Steward_MSSPQuarterlyMembership] (
    [MSSPQuarterlyMembershipKey]          INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                         VARCHAR (100) NULL,
    [CreateDate]                          DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                            VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                    VARCHAR (100) NULL,
    [LastUpdatedBy]                       VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                     DATETIME      DEFAULT (getdate()) NULL,
    [DataDate]                            DATE          NULL,
    [YearNBR]                             VARCHAR (10)  NULL,
    [QuarterNBR]                          VARCHAR (10)  NULL,
    [MedicareBeneficiaryID]               VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]             VARCHAR (50)  NULL,
    [FirstNM]                             VARCHAR (50)  NULL,
    [LastNM]                              VARCHAR (50)  NULL,
    [SexCD]                               VARCHAR (5)   NULL,
    [BirthDTS]                            DATE          NULL,
    [DeathDTS]                            DATE          NULL,
    [CountyNM]                            VARCHAR (50)  NULL,
    [HomeStateCD]                         VARCHAR (5)   NULL,
    [CountyNBR]                           VARCHAR (50)  NULL,
    [VoluntaryAlignmentFLG]               VARCHAR (5)   NULL,
    [VoluntaryAlignmentTIN]               VARCHAR (20)  NULL,
    [VoluntaryAlignmentNPI]               VARCHAR (20)  NULL,
    [ClaimsBasedAssignmentFLG]            VARCHAR (5)   NULL,
    [AssignmentStepCD]                    VARCHAR (5)   NULL,
    [NewlyAssignedBeneficiaryFLG]         VARCHAR (5)   NULL,
    [PartDMonthsEnrolledNBR]              VARCHAR (50)  NULL,
    [ExcludedFLG]                         VARCHAR (5)   NULL,
    [DeceasedExcludedFLG]                 VARCHAR (5)   NULL,
    [MissingIDExcludedFLG]                VARCHAR (5)   NULL,
    [PartAandBOnlyExcludeFLG]             VARCHAR (5)   NULL,
    [EmployerGroupHealthPlanExcludedFLG]  VARCHAR (5)   NULL,
    [OutsideUSExcludedFLG]                VARCHAR (5)   NULL,
    [OtherSharedSavingsInitiativesFLG]    VARCHAR (5)   NULL,
    [MonthlyEligibility01CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility02CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility03CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility04CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility05CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility06CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility07CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility08CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility09CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility10CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility11CD]              VARCHAR (5)   NULL,
    [MonthlyEligibility12CD]              VARCHAR (5)   NULL,
    [CMSHCCRiskScoreESRDNBR]              VARCHAR (50)  NULL,
    [CMSHCCRiskScoreDisabledStatusNBR]    VARCHAR (50)  NULL,
    [CMSHCCRiskScoreAgedDualStatusNBR]    VARCHAR (50)  NULL,
    [CMSHCCRiskScoreAgedNondualStatusNBR] VARCHAR (50)  NULL,
    [FileNM]                              VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPQuarterlyMembershipKey] ASC)
);

