CREATE TABLE [adi].[Steward_MSSPPartDClaimLineItem] (
    [MSSPPartDClaimLineItemKey]            INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                          VARCHAR (100) NULL,
    [CreateDate]                           DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                             VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                     VARCHAR (100) NULL,
    [LastUpdatedBy]                        VARCHAR (100) NULL,
    [LastUpdatedDate]                      DATETIME      NULL,
    [DataDate]                             DATE          NULL,
    [ClaimID]                              VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]                VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]              VARCHAR (50)  NULL,
    [NDC]                                  VARCHAR (50)  NULL,
    [ClaimTypeCD]                          VARCHAR (10)  NULL,
    [ClaimTypeDSC]                         VARCHAR (500) NULL,
    [PrescriptionFillDTS]                  DATE          NULL,
    [PharmacyIdentifierTypeCD]             VARCHAR (10)  NULL,
    [PharmacyIdentifierTypeDSC]            VARCHAR (500) NULL,
    [PharmacyID]                           VARCHAR (50)  NULL,
    [DispenseStatusCD]                     VARCHAR (10)  NULL,
    [DispenseStatusDSC]                    VARCHAR (500) NULL,
    [ProductSubstituteSelectionCD]         VARCHAR (10)  NULL,
    [ProductSubstituteSelectionDSC]        VARCHAR (500) NULL,
    [DispenseUnitCNT]                      VARCHAR (10)  NULL,
    [DispenseDaysCNT]                      INT           NULL,
    [PrescribingProviderIdentifierTypeCD]  VARCHAR (10)  NULL,
    [PrescribingProviderIdentifierTypeDSC] VARCHAR (500) NULL,
    [PrescribingProviderID]                VARCHAR (50)  NULL,
    [BeneficiaryPaymentAMT]                MONEY         NULL,
    [AdjustmentTypeCD]                     VARCHAR (10)  NULL,
    [AdjustmentTypeDSC]                    VARCHAR (500) NULL,
    [ProcessingDTS]                        DATE          NULL,
    [RepositoryLoadDTS]                    DATE          NULL,
    [PrescriptionReferenceNBR]             VARCHAR (50)  NULL,
    [PrescriptionFillSEQ]                  VARCHAR (10)  NULL,
    [PharmacyServiceTypeCD]                VARCHAR (10)  NULL,
    [FileNM]                               VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartDClaimLineItemKey] ASC)
);

