CREATE TABLE [adi].[Steward_MSSPBeneficiaryExclusion] (
    [MSSPBeneficiaryExclusionKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                 VARCHAR (100) NULL,
    [CreateDate]                  DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                    VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]            VARCHAR (100) NULL,
    [LastUpdatedBy]               VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]             DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                    DATE          NULL,
    [PerformanceYearNBR]          VARCHAR (50)  NULL,
    [ReportMonthNBR]              VARCHAR (50)  NULL,
    [FileCreationDTS]             DATE          NULL,
    [HealthInsuranceClaimNBR]     VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]       VARCHAR (50)  NULL,
    [FirstNM]                     VARCHAR (50)  NULL,
    [MiddleNM]                    VARCHAR (10)  NULL,
    [LastNM]                      VARCHAR (50)  NULL,
    [BirthDTS]                    DATE          NULL,
    [GenderCD]                    VARCHAR (10)  NULL,
    [GenderDSC]                   VARCHAR (100) NULL,
    [Reason01CD]                  VARCHAR (10)  NULL,
    [Reason01DSC]                 VARCHAR (100) NULL,
    [Reason02CD]                  VARCHAR (10)  NULL,
    [Reason02DSC]                 VARCHAR (100) NULL,
    [Reason03CD]                  VARCHAR (10)  NULL,
    [Reason03DSC]                 VARCHAR (100) NULL,
    [fileNM]                      VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPBeneficiaryExclusionKey] ASC)
);

