CREATE TABLE [adi].[Steward_MSSPPartBDMEClaimLineItem] (
    [MSSPPartBDMEClaimLineItemKey]    INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                     VARCHAR (100) NULL,
    [CreateDate]                      DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                        VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                VARCHAR (100) NULL,
    [LastUpdatedBy]                   VARCHAR (100) NULL,
    [LastUpdatedDate]                 DATETIME      NULL,
    [DataDate]                        DATE          NULL,
    [ClaimID]                         VARCHAR (50)  NULL,
    [LineNBR]                         VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]           VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]         VARCHAR (50)  NULL,
    [ClaimTypeCD]                     VARCHAR (10)  NULL,
    [ClaimTypeDSC]                    VARCHAR (500) NULL,
    [ClaimStartDTS]                   DATE          NULL,
    [ClaimEndDTS]                     DATE          NULL,
    [ServiceTypeCD]                   VARCHAR (10)  NULL,
    [ServiceTypeDSC]                  VARCHAR (500) NULL,
    [PlaceOfServiceCD]                VARCHAR (10)  NULL,
    [PlaceOfServiceNM]                VARCHAR (50)  NULL,
    [StartDTS]                        DATE          NULL,
    [EndDTS]                          DATE          NULL,
    [HCPCS]                           VARCHAR (50)  NULL,
    [PaymentAMT]                      MONEY         NULL,
    [PrimaryPayerCD]                  VARCHAR (10)  NULL,
    [PrimaryPayerDSC]                 VARCHAR (500) NULL,
    [PaidProviderNPI]                 VARCHAR (50)  NULL,
    [OrderingProviderNPI]             VARCHAR (50)  NULL,
    [CarrierPaymentDispositionCD]     VARCHAR (10)  NULL,
    [CarrierPaymentDispositionDSC]    VARCHAR (500) NULL,
    [LineProcessingIndicatorCD]       VARCHAR (10)  NULL,
    [LineProcessingIndicatorDSC]      VARCHAR (500) NULL,
    [AdjustmentTypeCD]                VARCHAR (10)  NULL,
    [AdjustmentTypeDSC]               VARCHAR (50)  NULL,
    [ProcessingDTS]                   DATE          NULL,
    [RepositoryLoadDTS]               DATE          NULL,
    [ControlNBR]                      VARCHAR (50)  NULL,
    [UmbrellaHealthInsuranceClaimNBR] VARCHAR (50)  NULL,
    [AllowedAMT]                      MONEY         NULL,
    [ClaimDispositionCD]              VARCHAR (10)  NULL,
    [ClaimDispositionDSC]             VARCHAR (500) NULL,
    [FileNM]                          VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartBDMEClaimLineItemKey] ASC)
);

