CREATE TABLE [adi].[Steward_MSSPPhonelist] (
    [MSSPPhonelistKey]                    INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                         VARCHAR (100) NULL,
    [CreateDate]                          DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                            VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                    VARCHAR (100) NULL,
    [LastUpdatedBy]                       VARCHAR (100) NULL,
    [LastUpdatedDate]                     DATETIME      NULL,
    [DataDate]                            DATE          NULL,
    [incoming_custacc]                    VARCHAR (50)  NULL,
    [incoming_fname]                      VARCHAR (20)  NULL,
    [incoming_mname]                      VARCHAR (20)  NULL,
    [incoming_lastname]                   VARCHAR (20)  NULL,
    [incoming_fullname]                   VARCHAR (100) NULL,
    [incoming_suffix]                     VARCHAR (10)  NULL,
    [incoming_ssn]                        VARCHAR (10)  NULL,
    [incoming_address1]                   VARCHAR (100) NULL,
    [incoming_address2]                   VARCHAR (100) NULL,
    [incoming_city]                       VARCHAR (100) NULL,
    [incoming_state]                      VARCHAR (50)  NULL,
    [incoming_zip]                        VARCHAR (15)  NULL,
    [incoming_dob]                        DATE          NULL,
    [incoming_phone]                      VARCHAR (20)  NULL,
    [incoming_client]                     VARCHAR (50)  NULL,
    [subj_phone]                          VARCHAR (20)  NULL,
    [subj_phone_listing_name]             VARCHAR (50)  NULL,
    [subj_phone_possible_relationship]    VARCHAR (20)  NULL,
    [subj_date_first_seen]                VARCHAR (20)  NULL,
    [subj_date_last_seen]                 VARCHAR (20)  NULL,
    [subj_phone_type]                     VARCHAR (50)  NULL,
    [subj_phone_duplicate_to_input_flag]  VARCHAR (10)  NULL,
    [subj_phone_line_type]                VARCHAR (50)  NULL,
    [subj_phone_ported_date]              VARCHAR (20)  NULL,
    [subj_phone2]                         VARCHAR (50)  NULL,
    [subj_phone_listing_name2]            VARCHAR (50)  NULL,
    [subj_phone_possible_relationship2]   VARCHAR (50)  NULL,
    [subj_date_first_seen2]               VARCHAR (20)  NULL,
    [subj_date_last_seen2]                VARCHAR (20)  NULL,
    [subj_phone_type2]                    VARCHAR (20)  NULL,
    [subj_phone_duplicate_to_input_flag2] VARCHAR (20)  NULL,
    [subj_phone_line_type2]               VARCHAR (20)  NULL,
    [subj_phone_ported_date2]             VARCHAR (20)  NULL,
    [subj_phone3]                         VARCHAR (50)  NULL,
    [subj_phone_listing_name3]            VARCHAR (50)  NULL,
    [subj_phone_possible_relationship3]   VARCHAR (50)  NULL,
    [subj_date_first_seen3]               VARCHAR (20)  NULL,
    [subj_date_last_seen3]                VARCHAR (20)  NULL,
    [subj_phone_type3]                    VARCHAR (50)  NULL,
    [subj_phone_duplicate_to_input_flag3] VARCHAR (50)  NULL,
    [subj_phone_line_type3]               VARCHAR (50)  NULL,
    [subj_phone_ported_date3]             VARCHAR (20)  NULL,
    [STATUS]                              SMALLINT      CONSTRAINT [DF_Steward_MsspPhoneList_RowStatus] DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([MSSPPhonelistKey] ASC)
);

