CREATE TABLE [adi].[Steward_MSSPDischargedMedicarePatients] (
    [DischargedMedicarePatientsKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                   VARCHAR (100) NULL,
    [CreateDate]                    DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                      VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]              VARCHAR (100) NULL,
    [LastUpdatedBy]                 VARCHAR (100) NULL,
    [LastUpdatedDate]               DATETIME      NULL,
    [DataDate]                      DATE          NULL,
    [FIN]                           VARCHAR (50)  NULL,
    [PriInsurance]                  VARCHAR (50)  NULL,
    [InsuranceMemberID]             VARCHAR (50)  NULL,
    [FName]                         VARCHAR (50)  NULL,
    [LName]                         VARCHAR (50)  NULL,
    [Birth]                         DATE          NULL,
    [IPAdmitDateTime]               DATETIME      NULL,
    [NurseUnit]                     VARCHAR (50)  NULL,
    [Room]                          VARCHAR (50)  NULL,
    [Address]                       VARCHAR (100) NULL,
    [Phone]                         VARCHAR (50)  NULL,
    [GMLOS]                         VARCHAR (50)  NULL,
    [DRG]                           VARCHAR (50)  NULL,
    [DRGDescription]                VARCHAR (100) NULL,
    [DischargeDateTime]             DATETIME      NULL,
    [DischargeDisposition]          VARCHAR (50)  NULL,
    [Attending]                     VARCHAR (50)  NULL,
    [AttendingNPI]                  VARCHAR (50)  NULL,
    [Surgeon]                       VARCHAR (50)  NULL,
    [Sex]                           VARCHAR (10)  NULL,
    [MRN]                           VARCHAR (50)  NULL,
    [Loc]                           VARCHAR (50)  NULL,
    [HospitalName]                  VARCHAR (50)  NULL,
    [HospNPI]                       VARCHAR (50)  NULL,
    [Status]                        CHAR (1)      CONSTRAINT [df_Status] DEFAULT ((0)) NULL,
    [RunDate]                       DATE          NULL,
    PRIMARY KEY CLUSTERED ([DischargedMedicarePatientsKey] ASC)
);

