CREATE TABLE [adi].[Steward_MSSPPartBPhysicianClaimLineItem] (
    [MSSPPartBPhysicianClaimLineItemKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                        VARCHAR (100) NULL,
    [CreateDate]                         DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                           VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                   VARCHAR (100) NULL,
    [LastUpdatedBy]                      VARCHAR (100) NULL,
    [LastUpdatedDate]                    DATETIME      NULL,
    [DataDate]                           DATE          NULL,
    [ClaimID]                            VARCHAR (50)  NULL,
    [LineNBR]                            VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]              VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]            VARCHAR (50)  NULL,
    [ClaimTypeCD]                        VARCHAR (10)  NULL,
    [ClaimTypeDSC]                       VARCHAR (500) NULL,
    [ClaimStartDTS]                      DATE          NULL,
    [ClaimEndDTS]                        DATE          NULL,
    [RenderingProviderTypeCD]            VARCHAR (10)  NULL,
    [RenderingProviderTypeDSC]           VARCHAR (500) NULL,
    [RenderingProviderFIPSStateCD]       VARCHAR (10)  NULL,
    [ProviderSpecialtyCD]                VARCHAR (10)  NULL,
    [ServiceTypeCD]                      VARCHAR (10)  NULL,
    [ServiceTypeDSC]                     VARCHAR (500) NULL,
    [PlaceOfServiceCD]                   VARCHAR (10)  NULL,
    [PlaceOfServiceNM]                   VARCHAR (50)  NULL,
    [StartDTS]                           DATE          NULL,
    [EndDTS]                             DATE          NULL,
    [HCPCS]                              VARCHAR (50)  NULL,
    [PaymentAMT]                         MONEY         NULL,
    [PrimaryPayerCD]                     VARCHAR (10)  NULL,
    [PrimaryPayerDSC]                    VARCHAR (500) NULL,
    [PrincipalICDDiagnosisCD]            VARCHAR (10)  NULL,
    [ClaimTaxID]                         VARCHAR (50)  NULL,
    [RenderingProviderNPI]               VARCHAR (50)  NULL,
    [CarrierPaymentDispositionCD]        VARCHAR (10)  NULL,
    [CarrierPaymentDispositionDSC]       VARCHAR (500) NULL,
    [LineProcessingIndicatorCD]          VARCHAR (10)  NULL,
    [LineProcessingIndicatorDSC]         VARCHAR (500) NULL,
    [AdjustmentTypeCD]                   VARCHAR (10)  NULL,
    [AdjustmentTypeDSC]                  VARCHAR (500) NULL,
    [ProcessingDTS]                      DATE          NULL,
    [RepositoryLoadDTS]                  DATE          NULL,
    [ControlNBR]                         VARCHAR (50)  NULL,
    [UmbrellaHealthInsuranceClaimNBR]    VARCHAR (50)  NULL,
    [AllowedAMT]                         MONEY         NULL,
    [AllowedUnitCNT]                     VARCHAR (5)   NULL,
    [HCPCSModifier01CD]                  VARCHAR (50)  NULL,
    [HCPCSModifier02CD]                  VARCHAR (50)  NULL,
    [HCPCSModifier03CD]                  VARCHAR (50)  NULL,
    [HCPCSModifier04CD]                  VARCHAR (50)  NULL,
    [HCPCSModifier05CD]                  VARCHAR (50)  NULL,
    [ClaimDispositionCD]                 VARCHAR (50)  NULL,
    [ClaimDispositionDSC]                VARCHAR (500) NULL,
    [ClaimICDDiagnosis01CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis02CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis03CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis04CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis05CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis06CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis07CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis08CD]              VARCHAR (50)  NULL,
    [ICDRevisionCD]                      VARCHAR (50)  NULL,
    [ClaimICDDiagnosis09CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis10CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis11CD]              VARCHAR (50)  NULL,
    [ClaimICDDiagnosis12CD]              VARCHAR (50)  NULL,
    [HCPCSBerensonEggersTypeOfServiceCD] VARCHAR (50)  NULL,
    [FileNM]                             VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartBPhysicianClaimLineItemKey] ASC)
);


GO
CREATE NONCLUSTERED INDEX [Ndx_StewardMSSPPartBPhysicianClaimLine_CLmIdMbiPdiagD1_D8]
    ON [adi].[Steward_MSSPPartBPhysicianClaimLineItem]([MSSPPartBPhysicianClaimLineItemKey] ASC, [LineNBR] ASC)
    INCLUDE([ClaimID], [MedicareBeneficiaryID], [PrincipalICDDiagnosisCD], [ClaimICDDiagnosis01CD], [ClaimICDDiagnosis02CD], [ClaimICDDiagnosis03CD], [ClaimICDDiagnosis04CD], [ClaimICDDiagnosis05CD], [ClaimICDDiagnosis06CD], [ClaimICDDiagnosis07CD], [ClaimICDDiagnosis08CD], [ICDRevisionCD], [ClaimICDDiagnosis09CD], [ClaimICDDiagnosis10CD], [ClaimICDDiagnosis11CD], [ClaimICDDiagnosis12CD]);

