CREATE TABLE [adi].[Steward_MSSPPartAClaimBenefitEnhancement] (
    [MSSPPartAClaimBenefitEnhancemenKey]                      INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                                             VARCHAR (100) NULL,
    [CreateDate]                                              DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                                                VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                                        VARCHAR (100) NULL,
    [LastUpdatedBy]                                           VARCHAR (100) NULL,
    [LastUpdatedDate]                                         DATETIME      NULL,
    [DataDate]                                                DATE          NULL,
    [ClaimID]                                                 VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]                                   VARCHAR (10)  NULL,
    [HealthInsuranceClaimNBR]                                 VARCHAR (50)  NULL,
    [ClaimTypeCD]                                             VARCHAR (10)  NULL,
    [ClaimAdmissionDTS]                                       DATE          NULL,
    [PopulationBasedPaymentBenefitEnhancementFLG]             VARCHAR (10)  NULL,
    [PostDischargeHomeVisitBenefitEnhancementFLG]             VARCHAR (10)  NULL,
    [SNFThreeDayWaiverBenefitEnhancementFLG]                  VARCHAR (10)  NULL,
    [TelehealthBenefitEnhancementFLG]                         VARCHAR (10)  NULL,
    [AllInclusivePopulationBasedPaymentBenefitEnhancementFLG] VARCHAR (10)  NULL,
    [FirstProgramDemonstrationNBR]                            VARCHAR (50)  NULL,
    [SecondProgramDemonstrationNBR]                           VARCHAR (50)  NULL,
    [ThirdProgramDemonstrationNBR]                            VARCHAR (50)  NULL,
    [FourthProgramDemonstrationNBR]                           VARCHAR (50)  NULL,
    [FifthProgramDemonstrationNBR]                            VARCHAR (50)  NULL,
    [PopulationBasedPaymentInclusionAMT]                      MONEY         NULL,
    [PopulationBasedPaymentReductionAMT]                      MONEY         NULL,
    [PlaceHolderTXT]                                          VARCHAR (500) NULL,
    [FileNM]                                                  VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartAClaimBenefitEnhancemenKey] ASC)
);

