CREATE TABLE [adi].[Steward_MSSPPartAClaimLineItem] (
    [MSSPPartAClaimLineItemKey]       INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                     VARCHAR (100) NULL,
    [CreateDate]                      DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                        VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                VARCHAR (100) NULL,
    [LastUpdatedBy]                   VARCHAR (100) NULL,
    [LastUpdatedDate]                 DATETIME      NULL,
    [DataDate]                        DATE          NULL,
    [ClaimID]                         VARCHAR (50)  NULL,
    [LineNBR]                         VARCHAR (50)  NULL,
    [MedicareBeneficiaryID]           VARCHAR (50)  NULL,
    [HealthInsuranceClaimNBR]         VARCHAR (50)  NULL,
    [ClaimTypeCD]                     VARCHAR (10)  NULL,
    [ClaimTypeDSC]                    VARCHAR (500) NULL,
    [StartDTS]                        DATE          NULL,
    [EndDTS]                          DATE          NULL,
    [RevenueCenterCD]                 VARCHAR (10)  NULL,
    [RevenueCenterDSC]                VARCHAR (500) NULL,
    [RevenueCenterDTS]                DATE          NULL,
    [HCPCS]                           VARCHAR (50)  NULL,
    [UmbrellaHealthInsuranceClaimNBR] VARCHAR (50)  NULL,
    [CMSCertificationNBR]             VARCHAR (50)  NULL,
    [ClaimStartDTS]                   DATE          NULL,
    [ClaimEndDTS]                     DATE          NULL,
    [AllowedUnitCNT]                  VARCHAR (5)   NULL,
    [PaymentAMT]                      MONEY         NULL,
    [HCPCSModifier01CD]               VARCHAR (10)  NULL,
    [HCPCSModifier02CD]               VARCHAR (10)  NULL,
    [HCPCSModifier03CD]               VARCHAR (10)  NULL,
    [HCPCSModifier04CD]               VARCHAR (10)  NULL,
    [HCPCSModifier05CD]               VARCHAR (10)  NULL,
    [RevenueAPCHIPPSCD]               VARCHAR (10)  NULL,
    [FileNM]                          VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([MSSPPartAClaimLineItemKey] ASC)
);

