CREATE TABLE [adi].[tmp_CC_data_TX] (
    [ServiceDate]                         DATE           NULL,
    [YearMonth]                           FLOAT (53)     NULL,
    [Quarter]                             NVARCHAR (25)  NULL,
    [PaidDate]                            DATE           NULL,
    [Paid_YearMonth]                      FLOAT (53)     NULL,
    [Patient_ID]                          FLOAT (53)     NULL,
    [Member ID]                           FLOAT (53)     NULL,
    [Patient_Name]                        NVARCHAR (100) NULL,
    [Initial]                             NVARCHAR (10)  NULL,
    [Member DOB]                          DATE           NULL,
    [Age]                                 FLOAT (53)     NULL,
    [Age_Category]                        NVARCHAR (25)  NULL,
    [CC Payor]                            NVARCHAR (25)  NULL,
    [Payor]                               NVARCHAR (25)  NULL,
    [Payor Group]                         NVARCHAR (25)  NULL,
    [npi_no]                              FLOAT (53)     NULL,
    [PCP Name]                            NVARCHAR (100) NULL,
    [PCP Chapter]                         NVARCHAR (50)  NULL,
    [Zip Code]                            FLOAT (53)     NULL,
    [PCP_Specialty]                       NVARCHAR (100) NULL,
    [ProcCode]                            FLOAT (53)     NULL,
    [Procedure]                           NVARCHAR (150) NULL,
    [Diag_Code]                           NVARCHAR (15)  NULL,
    [Diagnosis]                           NVARCHAR (150) NULL,
    [Provider_NPI]                        FLOAT (53)     NULL,
    [Provider]                            NVARCHAR (100) NULL,
    [Prof_Provider_Specialty]             NVARCHAR (100) NULL,
    [Prof_Provider_Classification]        NVARCHAR (100) NULL,
    [Facility]                            NVARCHAR (50)  NULL,
    [Facility_NPI]                        FLOAT (53)     NULL,
    [Leakage]                             NVARCHAR (15)  NULL,
    [FACILITY DOLLARS]                    FLOAT (53)     NULL,
    [Allowed_Other]                       FLOAT (53)     NULL,
    [Allowed_Professional]                FLOAT (53)     NULL,
    [Allowed_Total]                       FLOAT (53)     NULL,
    [Ambulance ?]                         NVARCHAR (15)  NULL,
    [Ambulance Name]                      NVARCHAR (50)  NULL,
    [ID]                                  NVARCHAR (50)  NULL,
    [Service_Line]                        NVARCHAR (50)  NULL,
    [Service Line Flag]                   NVARCHAR (5)   NULL,
    [Sub Service Line]                    NVARCHAR (50)  NULL,
    [Compass]                             NVARCHAR (50)  NULL,
    [DRGCode]                             NVARCHAR (5)   NULL,
    [DRG]                                 NVARCHAR (5)   NULL,
    [MDC]                                 NVARCHAR (150) NULL,
    [DischargeDate]                       NVARCHAR (30)  NULL,
    [ServiceDateYM]                       DATETIME       NULL,
    [Year_Month]                          DATETIME       NULL,
    [Days]                                NVARCHAR (5)   NULL,
    [Emergent]                            NVARCHAR (15)  NULL,
    [prof_provider_classification1]       NVARCHAR (50)  NULL,
    [DrgCode1]                            NVARCHAR (5)   NULL,
    [ProCode]                             NVARCHAR (15)  NULL,
    [Focus Category]                      NVARCHAR (50)  NULL,
    [Volume]                              FLOAT (53)     NULL,
    [Affiliation Prov]                    NVARCHAR (100) NULL,
    [Affiliation]                         NVARCHAR (100) NULL,
    [OON]                                 FLOAT (53)     NULL,
    [Steward]                             FLOAT (53)     NULL,
    [Specialist Flag]                     FLOAT (53)     NULL,
    [New Payor Group]                     NVARCHAR (100) NULL,
    [Specialist Allowed_Facility_OON]     NVARCHAR (100) NULL,
    [Specialist/PCP]                      NVARCHAR (100) NULL,
    [Allowed_Facility_OON]                FLOAT (53)     NULL,
    [Allowed_Facility_Steward]            FLOAT (53)     NULL,
    [Specialist Allowed_Facility_Steward] NVARCHAR (5)   NULL,
    [Specialist Volume]                   NVARCHAR (5)   NULL,
    [Specialist OON]                      NVARCHAR (100) NULL,
    [Specialist Steward]                  NVARCHAR (50)  NULL,
    [Specialist Allowed_Facility]         NVARCHAR (50)  NULL,
    [Reporting Category]                  NVARCHAR (50)  NULL,
    [PCP Region]                          NVARCHAR (50)  NULL,
    [ReportingCategory]                   NVARCHAR (50)  NULL,
    [ServiceDate - Year]                  FLOAT (53)     NULL,
    [DateKey]                             FLOAT (53)     NULL,
    [Service Date YM]                     DATETIME       NULL
);

