CREATE TABLE [dbo].[KPITarget] (
    [lstScoringSystemKey] VARCHAR (50)   NULL,
    [ClientKey]           VARCHAR (50)   NULL,
    [LOB]                 VARCHAR (50)   NULL,
    [LOB_State]           VARCHAR (50)   NULL,
    [EffectiveDate]       DATETIME       NULL,
    [ExpirationDate]      DATETIME       NULL,
    [Active]              VARCHAR (50)   NULL,
    [ScoringType]         VARCHAR (50)   NULL,
    [P4qIndicator]        VARCHAR (50)   NULL,
    [MeasureID]           VARCHAR (50)   NULL,
    [MeasureDesc]         VARCHAR (50)   NULL,
    [Score_A]             DECIMAL (9, 3) NULL,
    [Score_B]             DECIMAL (9, 3) NULL,
    [Score_C]             DECIMAL (9, 3) NULL,
    [Score_D]             DECIMAL (9, 3) NULL,
    [Score_E]             DECIMAL (9, 3) NULL,
    [Weight_1]            VARCHAR (50)   NULL,
    [Weight_2]            VARCHAR (50)   NULL,
    [Weight_3]            VARCHAR (50)   NULL,
    [Weight_4]            VARCHAR (50)   NULL,
    [Weight_5]            VARCHAR (50)   NULL,
    [AceQmWeight]         VARCHAR (50)   NULL,
    [AceCmWeight]         VARCHAR (50)   NULL,
    [Pq4BaseValue]        VARCHAR (50)   NULL,
    [CreatedDate]         VARCHAR (50)   NULL,
    [CreatedBy]           VARCHAR (50)   NULL,
    [LastUpdatedDate]     VARCHAR (50)   NULL,
    [LastUpdatedBy]       VARCHAR (50)   NULL,
    [SrcFileName]         VARCHAR (50)   NULL
);

