CREATE TABLE [dbo].[tmp_AHR_HL7_Report_Header] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [ClientName]    VARCHAR (25)   NULL,
    [ACE_Id]        VARCHAR (25)   NULL,
    [LastName]      VARCHAR (100)  NULL,
    [FirstName]     VARCHAR (100)  NULL,
    [SubscriberNo]  VARCHAR (50)   NULL,
    [PCP]           VARCHAR (50)   NULL,
    [PCP_LastName]  VARCHAR (100)  NULL,
    [PCP_FirstName] VARCHAR (100)  NULL,
    [DOB]           DATE           NULL,
    [CurrentAge]    INT            NULL,
    [Gender]        VARCHAR (1)    NULL,
    [Address1]      VARCHAR (100)  NULL,
    [Address2]      VARCHAR (100)  NULL,
    [City]          VARCHAR (50)   NULL,
    [State]         VARCHAR (2)    NULL,
    [Zip]           VARCHAR (10)   NULL,
    [Phone]         VARCHAR (20)   NULL,
    [PracticeID]    INT            NULL,
    [PracticeName]  VARCHAR (100)  NULL,
    [ACE_Guid]      VARCHAR (50)   NULL,
    [EMR_CLIENT_ID] VARCHAR (20)   NULL,
    [Risk_Score1]   DECIMAL (5, 2) NULL,
    [Risk_Score2]   DECIMAL (5, 2) NULL,
    [Risk_Band1]    VARCHAR (10)   NULL,
    [Risk_Band2]    VARCHAR (10)   NULL,
    [LOADDATE]      DATETIME       DEFAULT (sysdatetime()) NULL,
    [LOADEDBY]      VARCHAR (100)  DEFAULT (suser_sname()) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

